  [31morigin/HEAD[m -> origin/develop-v2
  [31morigin/banner_color_contrast[m
  [31morigin/chore/update-readme-env-details[m
  [31morigin/chore/whitelist-vscode-settings[m
  [31morigin/develop[m
  [31morigin/develop-v2[m
  [31morigin/dropdown-accessibility[m
  [31morigin/email-validation[m
  [31morigin/feat/map-context[m
  [31morigin/feature/about-add-gnl-logo[m
  [31morigin/feature/add-donorchoose-links[m
  [31morigin/feature/add-priority-filter[m
  [31morigin/feature/add-school-type[m
  [31morigin/feature/add-vince-about[m
  [31morigin/feature/age-sops-encryption[m
  [31morigin/feature/confirmation-email[m
  [31morigin/feature/dynamic-sitemap-seo[m
  [31morigin/feature/filter[m
  [31morigin/feature/filtered-schools-persistance[m
  [31morigin/feature/high-priority-modal-hover-banner[m
  [31morigin/feature/layout-enrolled-proficiency[m
  [31morigin/feature/map-copy-edit[m
  [31morigin/feature/marker-clustering[m
  [31morigin/feature/mobile-filter[m
  [31morigin/feature/new-posthog[m
  [31morigin/feature/nextjs-v16-upgrade[m
  [31morigin/feature/posthog[m
  [31morigin/feature/remove-sitemap-dev-autogen[m
  [31morigin/feature/search-dropdown-keyboard-accessibility[m
  [31morigin/feature/search-filter-toggle-redesign-desktop[m
  [31morigin/feature/volunteer-modals[m
  [31morigin/feature/x-close-map-card[m
  [31morigin/fix/faster-search-results[m
  [31morigin/fix/high-priority-label-centering[m
  [31morigin/fix/remove-autozoom-from-map-interaction[m
  [31morigin/fix/remove-autozoom-from-map-interaction-1[m
  [31morigin/fix/remove-autozoom-from-map-interaction-2[m
  [31morigin/fix/restore-page-height-fix[m
  [31morigin/fix/rollback-autozoom-on-click[m
  [31morigin/fix/rollback-autozoom-on-click-2[m
  [31morigin/fix/school-stats-appearance[m
  [31morigin/main[m
  [31morigin/main-posthog[m
  [31morigin/map-style-fix[m
  [31morigin/postgres_update_18[m
  [31morigin/posthog-check[m
  [31morigin/posthog-update[m
  [31morigin/refactor/aria-labeling[m
  [31morigin/refactor/aria-role[m
  [31morigin/refactor/fix-hide-keyboard[m
  [31morigin/refactor/fix-modal-zindex[m
  [31morigin/refactor/fix-vince-img-fname[m
  [31morigin/refactor/html-element-lang-prop[m
  [31morigin/refactor/icon-link[m
  [31morigin/refactor/map-escape-key[m
  [31morigin/refactor/map-list-switch-focus-ring[m
  [31morigin/refactor/map-page[m
  [31morigin/refactor/marker[m
  [31morigin/refactor/mobile-map-school-card[m
  [31morigin/refactor/nextjs-v14-to-v15-upgrade[m
  [31morigin/refactor/nextjs-v14-upgrade[m
  [31morigin/refactor/nextjs-v15-upgrade[m
  [31morigin/refactor/plausible-routing[m
  [31morigin/refactor/priority-filter-flag[m
  [31morigin/refactor/school-profile-update-25-08-26[m
  [31morigin/refactor/static-sitemap-generation[m
  [31morigin/refactor/sticky-search-next15[m
  [31morigin/refactor/update-static-images-0702[m
  [31morigin/refactor/volunteer-button-scroll-miss[m
  [31morigin/refactor/volunteer-component[m
  [31morigin/school-page-volunteer[m
  [31morigin/trushmi/update-about-page[m
  [31morigin/update_search[m
