import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
async function main() {
  await prisma.schools.createMany({
    data: [
      {
        name: "Balboa High School",
        address: "1000 Cayuga Ave, San Francisco, CA",
        sf_district: "Cayuga Terrace",
        students: 1230,
        free_reduced_lunch: "59",
        ell: "",
        color: "#3986ff",
        img: "img/balboa.jpg",
        latitude: "37.722",
        longitude: "-122.44041",
      },
      {
        name: "Burton High School",
        address: "400 Mansell St, San Francisco, CA",
        sf_district: "Portola",
        students: 1175,
        free_reduced_lunch: "64",
        ell: "",
        color: "#3986ff",
        img: "img/Burton_01a.jpg",
        latitude: "37.72126",
        longitude: "-122.4063",
      },
      {
        name: "Downtown High School",
        address: "693 Vermont St, San Francisco, CA",
        sf_district: "Potrero Hill",
        students:0,
        free_reduced_lunch: "",
        ell: "",
        color: "#3986ff",
        img: "img/downtown.jpg",
        latitude: "37.761565",
        longitude: "-122.40394",
      },
      {
        name: "Galileo Academy of Science & Technology",
        address: "1150 Francisco St, San Francisco, CA",
        sf_district: "Russian Hill",
        students: 1840,
        free_reduced_lunch: "61",
        ell: "21.2",
        color: "#3986ff",
        img: "img/galileo.jpg",
        latitude: "37.80379",
        longitude: "-122.424145",
      },
      {
        name: "Ida B. Wells High School",
        address: "1099 Hayes St, San Francisco, CA",
        sf_district: "Alamo Square",
        students:0,
        free_reduced_lunch: "",
        ell: "",
        color: "#3986ff",
        img: "img/idabwells.jpg",
        latitude: "37.7751",
        longitude: "-122.433985",
      },
      {
        name: "Independence High School",
        address: "1350 7th Ave, San Francisco, CA",
        sf_district: "Inner Sunset",
        students:0,
        free_reduced_lunch: "",
        ell: "",
        color: "#3986ff",
        img: "img/independence.png",
        latitude: "37.76309",
        longitude: "-122.46388",
      },
      {
        name: "International High School",
        address: "655 De Haro St, San Francisco, CA",
        sf_district: "Potrero Hill",
        students: 0,
        free_reduced_lunch: "",
        ell: "",
        color: "#3986ff",
        img: "img/intl.png",
        latitude: "37.76169",
        longitude: "-122.40082",
      },
      {
        name: "June Jordan School for Equity",
        address: "325 La Grande Ave, San Francisco, CA",
        sf_district: "Excelsior",
        students: 324,
        free_reduced_lunch: "65",
        ell: "48",
        color: "#3986ff",
        img: "img/june_jordan_school.png",
        latitude: "37.7195",
        longitude: "-122.42539",
      },
      {
        name: "Lincoln High School",
        address: "2162 24th Ave, San Francisco, CA",
        sf_district: "Parkside",
        students: 1990,
        free_reduced_lunch: "48",
        ell: "",
        color: "#3986ff",
        img: "img/lincoln.jpg",
        latitude: "37.74729",
        longitude: "-122.48109",
      },
      {
        name: "Lowell High School",
        address: "1101 Eucalyptus Dr, San Francisco, CA",
        sf_district: "Lakeshore",
        students: 0,
        free_reduced_lunch: "",
        ell: "",
        color: "#3986ff",
        img: "img/lowell.jpg",
        latitude: "37.73068",
        longitude: "-122.48392",
      },
      {
        name: "Mission High School",
        address: "3750 18th St, San Francisco, CA",
        sf_district: "Mission Dolores",
        students: 1040,
        free_reduced_lunch: "56",
        ell: "",
        color: "#3986ff",
        img: "img/Mission-High-School.jpg",
        latitude: "37.7616",
        longitude: "-122.42698",
      },
      {
        name: "John O'Connell Technical High School",
        address: "2355 Folsom St, San Francisco, CA",
        sf_district: "Mission",
        students: 525,
        free_reduced_lunch: "65",
        ell: "",
        color: "#3986ff",
        img: "img/johnoconnell.png",
        latitude: "37.75956",
        longitude: "-122.41454",
      },
      {
        name: "Ruth Asawa School of the Arts (SOTA)",
        address: "555 Portola Dr, San Francisco, CA",
        sf_district: "Glen Park",
        students: 0,
        free_reduced_lunch: "",
        ell: "",
        color: "#3986ff",
        img: "img/ruthasawa.jpg",
        latitude: "37.74538",
        longitude: "-122.44965",
      },
      {
        name: "The Academy",
        address: "550 Portola Dr, San Francisco, CA",
        sf_district: "Glen Park",
        students: 360,
        free_reduced_lunch: "55",
        ell: "",
        color: "#3986ff",
        img: "img/theacademy.png",
        latitude: "37.745499",
        longitude: "-122.451563",
      },
      {
        name: "Thurgood Marshall High School",
        address: "45 Conkling St, San Francisco, CA",
        sf_district: "Silver Terrace",
        students: 525,
        free_reduced_lunch: "62",
        ell: "",
        color: "#3986ff",
        img: "img/Thurgood-Marshall-Academic-High-School.jpg",
        latitude: "37.73609",
        longitude: "-122.40211",
      },
      {
        name: "Wallenberg High School",
        address: "40 Vega St, San Francisco, CA",
        sf_district: "Anza Vista",
        students: 0,
        free_reduced_lunch: "",
        ell: "",
        color: "#3986ff",
        img: "img/raoulwallenberg.jpg",
        latitude: "37.780365",
        longitude: "-122.44621",
      },
      {
        name: "George Washington High School",
        address: "600 32nd Ave, San Francisco, CA",
        sf_district: "Richmond",
        students: 2070,
        free_reduced_lunch: "46",
        ell: "",
        color: "#3986ff",
        img: "img/georgewashington.jpg",
        latitude: "37.77784",
        longitude: "-122.49174",
      },
    ],
    skipDuplicates: true,
  })
}
main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })