# Docker Compose file for setting up a PostgreSQL database for the SFUSD project

services:
  sfusd_db:
    image: postgres
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      # defaults should be overridden in .env file
      POSTGRES_PASSWORD: ${DB_PASSWORD:-supersecret}
      POSTGRES_DB: ${DB_NAME:-mydb}
    volumes:
      - sfusd-data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080

volumes:
  sfusd-data:
    driver: local
